on:
  workflow_dispatch:

jobs:
  libs:
    name: ceshi
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: install zstd
        run: |
          # fastmirror is to slow
          CENTOS_MIRROR='mirror.facebook.net/centos/'
          sed -i 's/^metalink=/#metalink=/g' /etc/yum.repos.d/*.repo
          sed -i 's/^mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/*.repo
          sed -i 's|^#baseurl=http://mirror\.centos\.org/centos/|baseurl=https://'$CENTOS_MIRROR'|g' /etc/yum.repos.d/*.repo
          yum install -yy zstd

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            /etc
          key: ceshiceshi1
