on:
  workflow_dispatch:

jobs:
  libs:
    name: ceshi
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: install zstd
        run: |
          yum install -yy zstd

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            /etc
          key: ceshiceshi1
