name: for msvc bug

on:
  workflow_dispatch:

jobs:
  ceshi:
    name: ceshi
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-latest"
            vs: "2022"
          - os: "windows-2019"
            vs: "2019"
      fail-fast: false
    steps:
      - name: ceshi
        shell: pwsh
        run: |
          # for Community
          #Enter-VsDevShell -VsInstallPath 'C:\Program Files\Microsoft Visual Studio\${{matrix.vs}}\Community\' -DevCmdArguments -arch=x64
          Enter-VsDevShell -VsInstallPath 'C:\Program Files\Microsoft Visual Studio\${{matrix.vs}}\Enterprise\' -DevCmdArguments -arch=x64
          Write-Output '
          int main()
          {
              struct wchar_codecvt : public std::codecvt<wchar_t, char, std::mbstate_t> {};
              std::wstring_convert<wchar_codecvt> converter;
              std::cout << "done" << std::endl;
              return 0;
          }
          ' | Out-File msvcbug.cxx

          & cl msvcbug.cxx -fsanitize=address /MDd /Z7 /EHsc
          & ./msvcbug.exe
