name: for msvc bug

on:
  workflow_dispatch:

jobs:
  ceshi:
    name: ceshi
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-latest"
            path: 'C:\Program Files\Microsoft Visual Studio\2022\$varient'
          - os: "windows-2019"
            path: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\$varient'
      fail-fast: false
    steps:
      - name: ceshi
        shell: pwsh
        run: |
          $varient = 'Enterprise'
          Import-Module "${{ matrix.path }}\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath "${{ matrix.path }}" -DevCmdArguments -arch=x64
          Write-Output '
          #include <locale>
          #include <iostream>
          int main()
          {
              struct wchar_codecvt : public std::codecvt<wchar_t, char, std::mbstate_t> {};
              std::wstring_convert<wchar_codecvt> converter;
              std::cout << "done" << std::endl;
              return 0;
          }
          ' | Out-File msvcbug.cxx

          & cl msvcbug.cxx -fsanitize=address /MDd /Z7 /EHsc
          & ./msvcbug.exe
