name: for msvc bug

on:
  workflow_dispatch:

jobs:
  ceshi:
    name: ceshi
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-latest"
            vs: "2022"
            mod: 'C:\Program Files\Microsoft Visual Studio\2022\$varient\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
          - os: "windows-2019"
            vs: "2019"
            mod: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\$varient\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
      fail-fast: false
    steps:
      - name: ceshi
        shell: pwsh
        run: |
          $varient = 'Enterprise'
          Import-Module "${{ matrix.mod }}"
          Enter-VsDevShell -VsInstallPath "C:\Program Files\Microsoft Visual Studio\${{matrix.vs}}\$varient\" -DevCmdArguments -arch=x64
          Write-Output '
          int main()
          {
              struct wchar_codecvt : public std::codecvt<wchar_t, char, std::mbstate_t> {};
              std::wstring_convert<wchar_codecvt> converter;
              std::cout << "done" << std::endl;
              return 0;
          }
          ' | Out-File msvcbug.cxx

          & cl msvcbug.cxx -fsanitize=address /MDd /Z7 /EHsc
          & ./msvcbug.exe
